//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demopopway.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Exam__Score
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Required")]
        public string subject { get; set; }
        [Required(ErrorMessage = "Required")]
        public int? score { get; set; }
        [Required(ErrorMessage = "Required")]
        public int? student_id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
